In [56]:
import pandas as pd
import numpy as np
df = pd.read_csv(r"D:\New folder (2)\python_dsa\ecommerce_data.csv")

In [57]:
df.head()

,OrderID,CustomerID,Gender,Age,City,Product,Category,Price,Quantity,OrderDate,PaymentMethod,Rating
0,1001,C101,Male,28,Bangalore,Phone,Electronics,20000,1,2024-01-10,UPI,4
1,1002,C102,Female,34,Delhi,Laptop,Electronics,55000,1,2024-01-11,Card,5
2,1003,C103,Male,22,Mumbai,Headphones,Electronics,2000,2,2024-01-12,COD,3
3,1004,C104,Female,45,Chennai,Sofa,Furniture,15000,1,2024-01-13,UPI,4
4,1005,C105,Male,30,Bangalore,T-shirt,Clothing,500,3,2024-01-14,Card,2

# Section 1 : Basic Pandas

In [58]:
# DataTypes of each column 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        12 non-null     int64
 1   CustomerID     12 non-null     object
 2   Gender         12 non-null     object
 3   Age            12 non-null     int64
 4   City           12 non-null     object
 5   Product        12 non-null     object
 6   Category       12 non-null     object
 7   Price          12 non-null     int64
 8   Quantity       12 non-null     int64
 9   OrderDate      12 non-null     object
 10  PaymentMethod  12 non-null     object
 11  Rating         12 non-null     int64
dtypes: int64(5), object(7)
memory usage: 1.3+ KB

In [59]:
# Shape of data
df.shape

(12, 12)

In [109]:
# Convert 'OrderDate' to datetime

df['OrderDate'] = pd.to_datetime(df['OrderDate'])
df['OrderID']= df['OrderID'].astype(object)

# Section 2: Data Cleaning

In [61]:
# Missing Values
df.isnull().sum()

OrderID          0
CustomerID       0
Gender           0
Age              0
City             0
Product          0
Category         0
Price            0
Quantity         0
OrderDate        0
PaymentMethod    0
Rating           0
dtype: int64

In [62]:
# Dropping Duplicates

df.drop_duplicates()

,OrderID,CustomerID,Gender,Age,City,Product,Category,Price,Quantity,OrderDate,PaymentMethod,Rating
0,1001,C101,Male,28,Bangalore,Phone,Electronics,20000,1,2024-01-10,UPI,4
1,1002,C102,Female,34,Delhi,Laptop,Electronics,55000,1,2024-01-11,Card,5
2,1003,C103,Male,22,Mumbai,Headphones,Electronics,2000,2,2024-01-12,COD,3
3,1004,C104,Female,45,Chennai,Sofa,Furniture,15000,1,2024-01-13,UPI,4
4,1005,C105,Male,30,Bangalore,T-shirt,Clothing,500,3,2024-01-14,Card,2
5,1006,C101,Male,28,Bangalore,Mouse,Electronics,800,2,2024-01-15,UPI,5
6,1007,C106,Female,26,Delhi,Dress,Clothing,1500,1,2024-01-16,COD,4
7,1008,C107,Male,35,Mumbai,Table,Furniture,7000,1,2024-01-17,Card,3
8,1009,C108,Female,29,Chennai,Phone,Electronics,18000,1,2024-01-18,UPI,5
9,1010,C109,Male,40,Bangalore,Chair,Furniture,3000,2,2024-01-19,COD,4
10,1011,C110,Female,31,Delhi,Laptop,Electronics,60000,1,2024-01-20,Card,5
11,1012,C111,Male,27,Mumbai,T-shirt,Clothing,700,2,2024-01-21,UPI,3

In [63]:
# Replacing values

df.replace(np.where(df['Rating']<3),'Nan',inplace=True)

In [64]:
df['Rating'].dtype

dtype('O')

In [65]:
# Convert object datatype to numeric
df['Rating'] = pd.to_numeric(df['Rating'],errors = 'coerce')

In [66]:
# Filling missing values

df['Rating']=df['Rating'].fillna(df['Rating'].mean())

# Section 3 : Filtering

In [67]:
df[df['City'] == "Bangalore"]

,OrderID,CustomerID,Gender,Age,City,Product,Category,Price,Quantity,OrderDate,PaymentMethod,Rating
0,1001,C101,Male,28,Bangalore,Phone,Electronics,20000,1,2024-01-10,UPI,3.875
4,1005,C105,Male,30,Bangalore,T-shirt,Clothing,500,3,2024-01-14,Card,2.000
5,1006,C101,Male,28,Bangalore,Mouse,Electronics,800,2,2024-01-15,UPI,5.000
9,1010,C109,Male,40,Bangalore,Chair,Furniture,3000,2,2024-01-19,COD,3.875

In [68]:
df[df['Age']>30]

,OrderID,CustomerID,Gender,Age,City,Product,Category,Price,Quantity,OrderDate,PaymentMethod,Rating
1,1002,C102,Female,34,Delhi,Laptop,Electronics,55000,1,2024-01-11,Card,5.000
3,1004,C104,Female,45,Chennai,Sofa,Furniture,15000,1,2024-01-13,UPI,3.875
7,1008,C107,Male,35,Mumbai,Table,Furniture,7000,1,2024-01-17,Card,3.000
9,1010,C109,Male,40,Bangalore,Chair,Furniture,3000,2,2024-01-19,COD,3.875
10,1011,C110,Female,31,Delhi,Laptop,Electronics,60000,1,2024-01-20,Card,5.000

# Section 4 : Feature Engineering

In [69]:
# Creating new column
df['TotalAmount'] = df['Price']* df['Quantity']

In [70]:
# Creating column based on condition 
conditions = [
    ((df['Age']>20) & (df['Age'] < 30)),
    ((df['Age'] >= 30) & (df['Age'] < 40)),
    (df['Age']>= 40 )
]
choices = ['Young','Adult','Senior']
df['Agegroup'] = np.select(conditions,choices,default = "Missing")

# Section 5: GroupBy

In [71]:
revenue_by_city = df.groupby('City')['TotalAmount'].sum()
revenue_by_city

City
Bangalore     29100
Chennai       33000
Delhi        116500
Mumbai        12400
Name: TotalAmount, dtype: int64

In [72]:
avg_rating_per_category = df.groupby('Category')['Rating'].mean().reset_index(name = 'Avg_rating')
avg_rating_per_category

      Category  Avg_rating
0     Clothing    2.958333
1  Electronics    4.479167
2    Furniture    3.583333

In [73]:
orders_per_payment_method = df.groupby('PaymentMethod')['OrderID'].count().reset_index(name= 'count')
orders_per_payment_method

  PaymentMethod  count
0           COD      3
1          Card      4
2           UPI      5

# Section 6 : Advanced Analysis

In [74]:
top_3_product = (
    df.groupby('Product')['TotalAmount']
    .sum()
    .sort_values(ascending=False)
    .reset_index()
    .head(3)
)
top_3_product

  Product  TotalAmount
0  Laptop       115000
1   Phone        38000
2    Sofa        15000

In [75]:
most_popular_category = (
    df.groupby('Category')['Quantity']
    .sum()
)
most_popular_category

Category
Clothing       6
Electronics    8
Furniture      4
Name: Quantity, dtype: int64

In [76]:
city_highest_revenue = (
    df.groupby('City')['TotalAmount']
    .sum()
    .sort_values(ascending = False)
    .reset_index()
    .head(1)
)
city_highest_revenue

    City  TotalAmount
0  Delhi       116500

# Section 7 : Sorting & Ranking

In [77]:
top_5_customers = (
    df.groupby('CustomerID',as_index=False)
      .agg({
          'TotalAmount': 'sum',
          'Age': 'first',
          'City': 'first'
      })
      .sort_values(by='TotalAmount', ascending=False)
      .head(5)
)

top_5_customers

  CustomerID  TotalAmount  Age       City
9       C110        60000   31      Delhi
1       C102        55000   34      Delhi
0       C101        21600   28  Bangalore
7       C108        18000   29    Chennai
3       C104        15000   45    Chennai

In [78]:
df['Rank'] = df['TotalAmount'].rank().astype(int)

In [79]:
# Ranking cities based on Sales

rank_cities = (
    df.groupby("City")['TotalAmount']
    .sum()
    .rank(method='dense',ascending=False)
    .astype(int)
    .reset_index(name = "Rank")
    .sort_values(by='Rank')

)

rank_cities

        City  Rank
2      Delhi     1
1    Chennai     2
0  Bangalore     3
3     Mumbai     4

## SECTION 8: Window Functions

In [80]:
df.columns

Index(['OrderID', 'CustomerID', 'Gender', 'Age', 'City', 'Product', 'Category',
       'Price', 'Quantity', 'OrderDate', 'PaymentMethod', 'Rating',
       'TotalAmount', 'Agegroup', 'Rank'],
      dtype='object')

In [81]:
# Running total of revenue

df['running_total'] = df.sort_values('OrderDate')['TotalAmount'].cumsum()
df['running_total']

0      20000
1      75000
2      79000
3      94000
4      95500
5      97100
6      98600
7     105600
8     123600
9     129600
10    189600
11    191000
Name: running_total, dtype: int64

In [82]:
# Rolling average of price (window=3)

df['rolling_avg'] = df.sort_values("OrderDate")['Price'].rolling(window=3).mean()
df[['OrderDate', 'rolling_avg']]

    OrderDate   rolling_avg
0  2024-01-10           NaN
1  2024-01-11           NaN
2  2024-01-12  25666.666667
3  2024-01-13  24000.000000
4  2024-01-14   5833.333333
5  2024-01-15   5433.333333
6  2024-01-16    933.333333
7  2024-01-17   3100.000000
8  2024-01-18   8833.333333
9  2024-01-19   9333.333333
10 2024-01-20  27000.000000
11 2024-01-21  21233.333333

In [83]:
# Rank orders within each city
df['CityRank'] = (
    df.groupby('City')['TotalAmount']
    .rank(method='dense',ascending=False)
    .astype(int)
)
df[['City', 'TotalAmount', 'CityRank']].sort_values(by=['City', 'CityRank'])

         City  TotalAmount  CityRank
0   Bangalore        20000         1
9   Bangalore         6000         2
5   Bangalore         1600         3
4   Bangalore         1500         4
8     Chennai        18000         1
3     Chennai        15000         2
10      Delhi        60000         1
1       Delhi        55000         2
6       Delhi         1500         3
7      Mumbai         7000         1
2      Mumbai         4000         2
11     Mumbai         1400         3

# SECTION 9: NumPy

In [84]:
# Convert Price column to NumPy array
price = np.array(df['Price'])
price

array([20000, 55000,  2000, 15000,   500,   800,  1500,  7000, 18000,
        3000, 60000,   700])

In [85]:
# Find: Mean,Median,Standard deviation
price_mean = round(np.mean(price),2)
price_median = round(np.median(price),2)
price_std = round(np.std(price),2)
print(f"Mean: {price_mean}, Median: {price_median}, Standard Deviation: {price_std}")

Mean: 15291.67, Median: 5000.0, Standard Deviation: 20069.9

In [86]:
# Normalize price values
df['Price_normalized'] = (df['Price'] - price_mean) / price_std
df['Price_normalized']

0     0.234597
1     1.978502
2    -0.662269
3    -0.014533
4    -0.737008
5    -0.722060
6    -0.687182
7    -0.413140
8     0.134945
9    -0.612443
10    2.227631
11   -0.727042
Name: Price_normalized, dtype: float64

In [89]:
# Find outliers using Z-score
z_scores = df['Price_normalized']
outliers = df[np.abs(z_scores) > 3]
outliers

Empty DataFrame
Columns: [OrderID, CustomerID, Gender, Age, City, Product, Category, Price, Quantity, OrderDate, PaymentMethod, Rating, TotalAmount, Agegroup, Rank, running_total, rolling_avg, CityRank, Price_normalized]
Index: []


# SECTION 10: Real Business Questions

In [90]:
# Which category generates highest revenue?

category_revenue = df.groupby('Category')['TotalAmount'].sum().sort_values(ascending=False)
category_revenue

Category
Electronics    158600
Furniture       28000
Clothing         4400
Name: TotalAmount, dtype: int64

In [93]:
# Which payment method is most used?

payment_method_counts = df['PaymentMethod'].value_counts()
payment_method_counts

PaymentMethod
UPI     5
Card    4
COD     3
Name: count, dtype: int64

In [94]:
# Do higher prices lead to better ratings?

price_rating_correlation = df['Price'].corr(df['Rating'])
price_rating_correlation

np.float64(0.6154270984597231)

In [97]:
# Which age group spends the most?
spent_by_age_group = df.groupby('Agegroup')['TotalAmount'].sum()
spent_by_age_group

Agegroup
Adult     123500
Senior     21000
Young      46500
Name: TotalAmount, dtype: int64

In [101]:
# Which city has lowest average rating?

lowest_avg_rating = df.groupby('City')['Rating'].mean().sort_values().reset_index(name='Avg_Rating')
lowest_avg_rating

        City  Avg_Rating
0     Mumbai      3.0000
1  Bangalore      3.6875
2    Chennai      4.4375
3      Delhi      4.6250

# Section 11 : Advanced Analysis

In [105]:
# Pivot tables
pivot_table = df.pivot_table(
    index='City',
    columns='Category',
    values='TotalAmount',
    aggfunc='mean'
)

pivot_table

Category   Clothing  Electronics  Furniture
City
Bangalore    1500.0      10800.0     6000.0
Chennai         NaN      18000.0    15000.0
Delhi        1500.0      57500.0        NaN
Mumbai       1400.0       4000.0     7000.0

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   OrderID           12 non-null     object
 1   CustomerID        12 non-null     object
 2   Gender            12 non-null     object
 3   Age               12 non-null     int64
 4   City              12 non-null     object
 5   Product           12 non-null     object
 6   Category          12 non-null     object
 7   Price             12 non-null     int64
 8   Quantity          12 non-null     int64
 9   OrderDate         12 non-null     datetime64[ns]
 10  PaymentMethod     12 non-null     object
 11  Rating            12 non-null     float64
 12  TotalAmount       12 non-null     int64
 13  Agegroup          12 non-null     object
 14  Rank              12 non-null     int64
 15  running_total     12 non-null     int64
 16  rolling_avg       10 non-null     float64
 17  CityRank          12 non-null     int64
 18  Price_normalized  12 non-null     float64
dtypes: datetime64[ns](1), float64(3), int64(7), object(8)
memory usage: 1.9+ KB

In [113]:
# correlation matrix

correlation_matrix = df.select_dtypes(include=['number']).corr()
correlation_matrix

,Age,Price,Quantity,Rating,TotalAmount,Rank,running_total,rolling_avg,CityRank,Price_normalized
Age,1.000000,0.174937,-0.222288,0.107661,0.179116,0.334281,0.043297,0.051703,-0.189837,0.174937
Price,0.174937,1.000000,-0.541937,0.615427,0.999098,0.836493,0.126002,0.499252,-0.506253,1.000000
Quantity,-0.222288,-0.541937,1.000000,-0.593306,-0.521722,-0.673470,0.109723,-0.085860,0.744445,-0.541937
Rating,0.107661,0.615427,-0.593306,1.000000,0.613018,0.626358,0.074109,0.069460,-0.447420,0.615427
TotalAmount,0.179116,0.999098,-0.521722,0.613018,1.000000,0.836413,0.132492,0.513323,-0.503719,0.999098
Rank,0.334281,0.836493,-0.673470,0.626358,0.836413,1.000000,-0.150143,0.382325,-0.823284,0.836493
running_total,0.043297,0.126002,0.109723,0.074109,0.132492,-0.150143,1.000000,0.401039,0.059335,0.126002
rolling_avg,0.051703,0.499252,-0.085860,0.069460,0.513323,0.382325,0.401039,1.000000,-0.274816,0.499252
CityRank,-0.189837,-0.506253,0.744445,-0.447420,-0.503719,-0.823284,0.059335,-0.274816,1.000000,-0.506253
Price_normalized,0.174937,1.000000,-0.541937,0.615427,0.999098,0.836493,0.126002,0.499252,-0.506253,1.000000